export const SEARCH_TXT = 'SEARCH_TXT';
export const FILTER_DEPARTMENT = 'FILTER_DEPARTMENT';
export const SET_PAGE = 'SET_PAGE';
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const SET_SCROLLING = 'SET_SCROLLING';
export const RESET_PRODUCTS = 'RESET_PRODUCTS';